services:
  - type: web
    name: tracking-backend
    env: node
    plan: standard
    buildCommand: rm -rf node_modules/.prisma && npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
